katalog/urls.py
# Implement Routings Here
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
import imp
from django.urls import path

from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user 
from todolist.views import show_todolist
from todolist.views import create_new_task
from todolist.views import update_status
from todolist.views import delete_task, show_json,add_task
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_new_task, name='create-new-task'),
    path('update-status/<int:pk>', update_status, name='update-status'),
    path('delete-task/<int:pk>', delete_task, name='delete-task'),
    path('json/', show_json, name='show_json'),
    path('add/', add_task, name='add_task'),
]

todolist/models.py
from gc import is_finalized
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add = True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/views.py
from django.shortcuts import render
from todolist.models import Task
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist = Task.objects.filter(user=request.user)
    date = datetime.datetime.now()
    context = {
    'list_task': todolist,
    'user':request.user.username,
    'date':date,
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    return response

def create_new_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.now()
        user = request.user
        new_task = Task(user=user, title=title, description=description, date=date)
        new_task.save()
        response = HttpResponseRedirect(reverse("todolist:show_todolist")) 
        return response

    return render(request, "create-new-task.html")

def delete_task(request, pk):
    Task.objects.filter(id=pk).delete()
    return redirect("todolist:show_todolist")

def update_status(request, pk):
    task = Task.objects.get(id=pk)
    task.is_finished = not(task.is_finished)
    task.save()
    return redirect('todolist:show_todolist')
    
@login_required(login_url='/todolist/login')
def show_json(request):

    tasks = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", tasks), content_type="application/json")

@csrf_exempt
@login_required(login_url="/todolist/login/")
def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.today()
        user = request.user
        new_task = Task(user=user, title=title, description=description, date=date)
        new_task.save()
        return JsonResponse(
            {
            "title": title,
            "date": date,
            "description": description,
            "is_finished": False,
        }, status=200)

todolist/templates/create-new-task.html
{% extends 'base.html' %}

{% block meta %}
{% load static %}
<link rel="stylesheet" href="{% static 'style.css'%}">
{% endblock meta %}

{% block content %}

<div class = "login">
    <div class = "login">
        <div class="card login-form">
            <div class="card-body">
                <h1 class="card-title text-center">Create New Task</h2>
            </div>
            <div class="card-text">
    
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Title: </td>
                        <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Description: </td>
                        <td><input type="text" name="description" placeholder="Description" class="form-control"></td>
                    </tr>
        
                    <tr>
                        <td></td>
                        <td>
                            <div class="d-grid gap-2">
                            <input class="btn login_btn" type="submit" value="Create Task">
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        </div>
    </div>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% load static %}
<link rel="stylesheet" href="{% static 'style.css'%}">
{% endblock meta %}

{% block content %}

<div class = "login">
    <div class="card login-form">
        <div class="card-body">
            <h2 class="card-title text-center">Login</h2>
        </div>
        <div class="card-text">

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                    <td></td>
                    <td>
                        <div class="d-grid gap-2">
                        <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
    </div>
    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% load static %}
<link rel="stylesheet" href="{% static 'style.css'%}">

{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <div class="card register-form">


    <h1 class="card-title text-center">Register</h1> <br>

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td>
                        <input class="btn login_btn" type="submit" name="submit" value="Daftar"/>
                        <p>Sudah punya akun? <a href="{% url 'todolist:login' %}">login</a></p> 
                        
                    </td>  
                </tr>  
            </table>
             
        </form><br>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}
</div>
</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% block meta %}
<title>To-do list</title>
{% load static %}
<link rel="stylesheet" href="{% static 'style.css'%}">
<script>
        $(document).ready(function(){
            $.getJSON("{% url 'todolist:show_json' %}", function(task){
                $.each(task, function(index,value){
                console.log(value)
                    $("#todolist_container").append(
                    `<div class="col-12 col-md-6 col-lg-4">
                            <div class="card">
                                <h5 class="card-title">${value.fields.title}</h5>
                                <p class="card-text">${value.fields.date}.</p>
                                <p class="card-text">${value.fields.description}.</p>
                                <p class="card-text">Finished : ${value.fields.is_finished}.</p>
                            </div>
                        
                            </div>`    
                    )
                })
        })
        $("#form_todolist").on("submit",function(e) {
        e.preventDefault() 
        let date = $("#date").val();
        let title = $("#title").val();
        let description = $("#description").val();
        $.ajax({
          method: "POST",
          url: "/todolist/add/",
          data: {"date":date, "title":title, "description":description},
        }).done(function(resp) {
          console.log(resp)
          $("#todolist_container").append(
            `<div class="col-12 col-md-6 col-lg-4">
                            <div class="card">

                                <h5 class="card-title">${resp.title}</h5>
                                <p class="card-text">${resp.date}.</p>
                                <p class="card-text">${resp.description}.</p>
                                <p class="card-text">Finished : ${resp.is_finished}.</p>
                            </div>
                        </div>`    
          )
          $("#exampleModal").modal("toggle")
        });
    })
    })

</script>
{% endblock meta %}
{% block content %}

<!--navbar-->
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <h1 class="navbar-brand">Hello, {{user}}</h1>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <div class="container">
                <a href="{% url 'todolist:logout' %}"><button class="btn">Logout</button></a>
              </div>
          </li>
          <li class="nav-item">
            <div class="container">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Create New Task</button>
            </div>
        </li>
        </ul>
      </div>
    </div>
  </nav>
<!---->
<h2>Date : {{date}}</h2>

<!--modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Create New Task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form_todolist" action = "/todolist/add/">
            {% csrf_token%}
          <div class="mb-3">
            <label for="title" class="col-form-label">Title:</label>
            <input type="text" class="form-control" id="title">
          </div>
          <div class="mb-3">
            <label for="description" class="col-form-label">Description:</label>
            <textarea class="form-control" id="description"></textarea>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" value="submit" class="btn btn-primary" id="submit_btn">Create</button>
          </div>
        </form>
      </div>

    </div>
  </div>
</div>
<!----> 

  <div class="row g-3" id = "todolist_container">

  </div>
{% endblock content %}